tasks:
  - name: Pip
    init: >
      pip install dash jupyter-dash pandas &&
      gp sync-done pip

  - name: App
    init: gp sync-await pip
    command: >
      gp open app.py &&
      python app.py
    
ports:
  - port: 8050
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
